import type { Category, Draft, Listing } from './types'

export const seedListings: Listing[] = [
  { id: 1, name: 'Mbare Greenbelt Plot', area: 'Harare South, Harare', size: '2.4 hectares', price: '$180 / season', detail: 'Jun - Nov 2026', crop: 'Leafy greens', category: 'Vegetables', image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1000&q=85', tags: ['Borehole', 'Fenced'], featured: true, rating: 4.9, description: 'A well-drained greenbelt plot with a working borehole and full perimeter fencing. Previous seasons grew rape, covo and spinach for the Mbare market.' },
  { id: 2, name: 'Chitungwiza Orchard Land', area: 'Manyame, Mashonaland East', size: '1.8 hectares', price: '$95 / month', detail: 'Flexible term', crop: 'Horticulture', category: 'Orchards', image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1000&q=85', tags: ['Irrigation', 'Storage'], rating: 4.7, description: 'Established drip irrigation lines across gently sloping land, with a lockable storage shed on site for tools and harvest.' },
  { id: 3, name: 'Borrowdale Smallholding', area: 'Borrowdale, Harare', size: '0.75 hectares', price: '$75 / month', detail: '12 month lease', crop: 'Herbs & vegetables', category: 'Vegetables', image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1000&q=85', tags: ['Shed', 'Power nearby'], rating: 4.8, description: 'A compact, easy-to-manage plot close to the city, suited to herbs and market vegetables. Grid power is available at the boundary.' },
  { id: 4, name: 'Norton River Flats', area: 'Norton, Mashonaland West', size: '4.1 hectares', price: '$260 / season', detail: 'Jun - Nov 2026', crop: 'Maize & beans', category: 'Grains', image: 'https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?auto=format&fit=crop&w=1000&q=85', tags: ['River access', 'Tilled'], rating: 4.6, description: 'Flat, already-tilled river-flat land with direct water access, previously used for a maize and bean rotation.' },
  { id: 5, name: 'Kadoma Market Garden', area: 'Kadoma, Mashonaland West', size: '1.1 hectares', price: '$65 / month', detail: 'Flexible term', crop: 'Cabbage & lettuce', category: 'Vegetables', image: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=1000&q=85', tags: ['Borehole', 'Fenced'], rating: 4.5, description: 'Raised beds already laid out for market vegetables, close to Kadoma’s produce market. Borehole water and fencing are in place.' },
  { id: 6, name: 'Marondera Greens Plot', area: 'Marondera, Mashonaland East', size: '0.9 hectares', price: '$58 / month', detail: '6 month lease', crop: 'Cabbage', category: 'Vegetables', image: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=1000&q=85', tags: ['Irrigation', 'Fenced'], rating: 4.4, description: 'A tidy market-garden plot with drip irrigation already run through, previously cropped with cabbage and covo on a short rotation.' },
  { id: 7, name: 'Chegutu Grain Fields', area: 'Chegutu, Mashonaland West', size: '5.2 hectares', price: '$310 / season', detail: 'Jun - Nov 2026', crop: 'Maize (grain)', category: 'Grains', image: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=1000&q=85', tags: ['Tilled', 'Power nearby'], rating: 4.6, description: 'Open, already-tilled grain land large enough for a full maize rotation, with grid power at the access road for pumps or drying equipment.' },
  { id: 8, name: 'Gweru Wheatlands', area: 'Gweru, Midlands', size: '6.8 hectares', price: '$420 / season', detail: 'Apr - Sep 2026', crop: 'Wheat (grain)', category: 'Grains', image: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=1000&q=85', tags: ['River access', 'Tilled'], rating: 4.7, description: 'Established winter wheat ground on the Midlands plateau, gently sloped for drainage with river access for supplementary irrigation.' },
  { id: 9, name: 'Mutare Highlands Orchard', area: 'Mutare, Manicaland', size: '3.5 hectares', price: '$340 / season', detail: '12 month lease', crop: 'Avocado & macadamia', category: 'Orchards', image: 'https://images.unsplash.com/photo-1620200423727-8127f75d7f53?auto=format&fit=crop&w=1000&q=85', tags: ['Irrigation', 'Storage'], rating: 4.9, description: 'Established highland orchard rows with a cool, reliable climate for avocado and macadamia, plus on-site storage for harvest sorting.' },
  { id: 10, name: 'Bindura Apple Grove', area: 'Bindura, Mashonaland Central', size: '2.6 hectares', price: '$275 / season', detail: 'Flexible term', crop: 'Apples', category: 'Orchards', image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=1000&q=85', tags: ['Fenced', 'Storage'], rating: 4.5, description: 'A fenced apple grove with a small on-site store for grading and packing fruit ahead of sale.' },
  { id: 11, name: 'Chinhoyi Valley Gardens', area: 'Chinhoyi, Mashonaland West', size: '1.4 hectares', price: '$70 / month', detail: 'Flexible term', crop: 'Potatoes', category: 'Vegetables', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1000&q=85', tags: ['Irrigation', 'Storage'], rating: 4.6, description: 'Rich valley soil already worked for a potato crop, with irrigation lines and a small store for curing and grading tubers.' },
  { id: 12, name: 'Masvingo Market Plot', area: 'Masvingo, Masvingo', size: '0.85 hectares', price: '$60 / month', detail: '6 month lease', crop: 'Tomatoes', category: 'Vegetables', image: 'https://images.unsplash.com/photo-1598512752271-33f913a5af13?auto=format&fit=crop&w=1000&q=85', tags: ['Borehole', 'Fenced'], rating: 4.5, description: 'A fenced tomato plot with a reliable borehole, a short drive from Masvingo’s produce market.' },
  { id: 13, name: 'Karoi Grain Belt', area: 'Karoi, Mashonaland West', size: '4.6 hectares', price: '$290 / season', detail: 'Jun - Nov 2026', crop: 'Sorghum (grain)', category: 'Grains', image: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=1000&q=85', tags: ['Tilled', 'River access'], rating: 4.5, description: 'Freshly tilled grain land with young rows already established, plus river access for topping up irrigation in a dry spell.' },
  { id: 14, name: 'Rusape Fruit Basket', area: 'Rusape, Manicaland', size: '2.2 hectares', price: '$230 / season', detail: '12 month lease', crop: 'Mixed orchard fruit', category: 'Orchards', image: 'https://images.unsplash.com/photo-1573246123716-6b1782bfc499?auto=format&fit=crop&w=1000&q=85', tags: ['Storage', 'Power nearby'], rating: 4.4, description: 'A mixed fruit block — citrus, avocado and pear — with a grid-power packhouse for sorting and storing the harvest.' },
]

export const categories: ('All land' | Category)[] = ['All land', 'Vegetables', 'Grains', 'Orchards']
export const TAG_OPTIONS = ['Borehole', 'Fenced', 'Irrigation', 'Storage', 'Shed', 'Power nearby', 'River access', 'Tilled']
export const STEPS = ['Basics', 'Crop & features', 'Price & term', 'Photo', 'Review']
export const PLACEHOLDER_IMAGE = 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=85'
export const MY_LISTINGS_KEY = 'landlease-my-listings'
export const SAVED_KEY = 'landlease-saved'
export const emptyDraft: Draft = { name: '', area: '', size: '', crop: '', category: 'Vegetables', tags: [], price: '', unit: 'season', detail: '', image: '', description: '' }

export function loadMyListings(): Listing[] {
  try { return JSON.parse(localStorage.getItem(MY_LISTINGS_KEY) ?? '[]') } catch { return [] }
}
export function loadSaved(): number[] {
  try { return JSON.parse(localStorage.getItem(SAVED_KEY) ?? '[2]') } catch { return [2] }
}
export function listingToDraft(listing: Listing): Draft {
  const [price, unit] = listing.price.replace('$', '').split(' / ')
  return { name: listing.name, area: listing.area, size: listing.size, crop: listing.crop, category: listing.category, tags: listing.tags, price, unit: unit === 'month' ? 'month' : 'season', detail: listing.detail, image: listing.image, description: listing.description ?? '' }
}
