import { useState } from 'react'
import { Link } from 'react-router-dom'
import { demoListings } from '../lib/data'
import { BoundaryMap } from './BoundaryMap'
import { cropGuides } from './advisory'

const KEY = 'landlease-full-demo-v1'
const stages = ['Profile','List and map','Verification and soil','Farm visit','Negotiation','Witnesses','Agreement','Payment','Active lease','Support and rating']
type Demo = { step: number; name: string; role: string; plot: number; boundary: string; photo: string; submitted: boolean; verified: boolean; soil: boolean; visit: string; date: string; terms: string; proposal: string; counter: string; witnesses: string[]; signatures: string[]; paid: boolean; amount: number; plan: string; dispute: string; resolution: string; rating: string; messages: string[] }
const initial: Demo = { step: 0, name: 'Demo Farmer', role: 'landowner', plot: -1, boundary: '', photo: '', submitted: false, verified: false, soil: false, visit: 'none', date: '', terms: 'Example only: USD 1,080 total for a six-month vegetable lease. Irrigation and road access included. No live land or money is involved.', proposal: 'draft', counter: '', witnesses: ['', ''], signatures: ['', ''], paid: false, amount: 1080, plan: '', dispute: '', resolution: '', rating: '', messages: [] }
function read(): Demo {
  try { const value = JSON.parse(localStorage.getItem(KEY) || 'null');return value && value.step >= 0 && value.step < stages.length ? { ...initial, ...value } : initial } catch { return initial }
}
export function PresentationDemoPage() {
  const [demo, setDemo] = useState<Demo>(read)
  const [error, setError] = useState('')
  const [chat, setChat] = useState('')
  const [confirmAgreement, setConfirmAgreement] = useState(false)
  const [crop, setCrop] = useState<keyof typeof cropGuides>('Leafy vegetables')
  const [budget, setBudget] = useState('350')
  const [issue, setIssue] = useState('')
  const plot = demoListings.find(l => l.id === demo.plot) || demoListings[0]
  const commission = Math.round(demo.amount * 3) / 100
  function update(patch: Partial<Demo>) {
    const next = { ...demo, ...patch }
    try { localStorage.setItem(KEY, JSON.stringify(next));setDemo(next);setError('') } catch { setError('Browser storage is full or disabled. Remove the demo photo or allow browser storage.') }
  }
  function go(step: number, patch: Partial<Demo> = {}) { update({ ...patch, step }) }
  function reset() { localStorage.removeItem(KEY);setDemo(initial);setConfirmAgreement(false);setError('') }
  async function photo(file?: File) {
    if (!file) return
    if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) { setError('Choose a JPG, PNG or WebP smaller than 2 MB for browser storage.');return }
    const reader = new FileReader();reader.onload = () => update({ photo: String(reader.result) });reader.readAsDataURL(file)
  }
  const agreement = `DEMO AGRICULTURAL LEASE — NOT A REAL CONTRACT\nPlot: ${plot.name}\nLandowner: Demo Landowner\nTenant: ${demo.name}\nTotal lease value: USD ${demo.amount.toFixed(2)}\nTerm: six months, example only\nUse: ${plot.crop}; illustrative boundaries only\nWater and access: sample irrigation and road access\nLandowner responsibilities: maintain agreed access and water arrangements.\nTenant responsibilities: follow the agreed farming use, care for soil and return the plot at lease end.\nDisputes: record the concern in the support dashboard for a simulated review.\nWitnesses: ${demo.witnesses.join(' and ')}\nAccepted terms: ${demo.terms}\nThis document is a presentation sample, with simulated identities, signatures and payment.`
  const ready = [true,true,demo.submitted,demo.verified && demo.soil,demo.visit === 'confirmed',demo.proposal === 'accepted',demo.witnesses.every(Boolean),demo.signatures.every(Boolean),demo.paid,demo.paid]
  return <section className="container-xxl py-5" style={{ maxWidth: 1000 }}>
    <div className="d-flex justify-content-between align-items-start gap-3"><div><p className="text-primary fw-bold small text-uppercase">Presentation demo</p><h1>Landlease complete walkthrough</h1></div><button className="btn btn-outline-danger" onClick={reset}>Reset demo</button></div>
    <p className="alert alert-warning">DEMO ONLY · All listings, verification, laboratory results, signatures and payments here are simulated. Data stays in this browser. No real account, lease, appointment or payment is created.</p>
    <div className="d-flex gap-2 flex-wrap mb-3">{stages.map((label,index) => <button key={label} disabled={!ready[index]} onClick={() => go(index)} className={demo.step === index ? 'btn btn-dark btn-sm' : 'btn btn-outline-secondary btn-sm'}>{index + 1}. {label}</button>)}</div>
    <p className="small text-secondary">Simulated role: <select value={demo.role} onChange={e => update({ role: e.target.value })} className="form-select d-inline-block w-auto"><option value="landowner">Landowner</option><option value="tenant">Tenant</option><option value="admin">Admin</option></select> · You may switch roles during the presentation.</p>
    <div className="card p-4">
    <h2 className="h4">{stages[demo.step]}</h2>
    {demo.step === 0 && <><label>Demo tenant name<input className="form-control mb-3" value={demo.name} disabled={demo.signatures.some(Boolean)} onChange={e => update({ name: e.target.value })} /></label><p>In the real app, users create an account, verify email, choose tenant or landowner and enter contact information.</p><button disabled={demo.name.trim().length < 3} className="btn btn-primary align-self-start" onClick={() => go(1, { role: 'landowner' })}>Save demo profile and continue</button></>}
    {demo.step === 1 && <><label>Sample crop plot<select className="form-select mb-3" value={demo.plot} disabled={demo.submitted} onChange={e => update({ plot: Number(e.target.value) })}>{demoListings.map(l => <option key={l.id} value={l.id}>{l.category} · {l.name}</option>)}</select></label><img src={demo.photo || plot.image} alt="Illustrative demo plot" style={{ width: '100%', maxHeight: 260, objectFit: 'cover' }} className="rounded mb-3" /><label>Optional demo photo from laptop<input type="file" accept="image/jpeg,image/png,image/webp" className="form-control mb-3" disabled={demo.submitted} onChange={e => void photo(e.target.files?.[0])} /></label><p>{plot.area} · {plot.size} · {plot.crop} · {plot.price}<br />Example history: previously cultivated; irrigation indicated by sample listing.</p><BoundaryMap value={demo.boundary} onChange={boundary => update({ boundary })} readOnly={demo.submitted} /><p>Draw at least three corners on the map. These boundaries are for illustration.</p><button disabled={!demo.boundary} className="btn btn-primary align-self-start" onClick={() => go(2, { submitted: true, role: 'admin' })}>Submit demo listing for review</button></>}
    {demo.step === 2 && <><p>Sample ID and right-to-lease evidence are reviewed by the simulated administrator. Do not upload actual identity documents here.</p><ul><li>Identity: {demo.verified ? 'Simulated review complete; sample document deleted' : 'Awaiting demo review'}</li><li>Land rights: {demo.verified ? 'Simulated review complete' : 'Awaiting demo review'}</li><li>Soil test: {demo.soil ? 'Simulated fee and laboratory result complete · illustrative pH 6.5' : 'Awaiting simulated laboratory test'}</li></ul><p>The real app requires a laboratory partner and agreed test fee. This button illustrates those steps; it does not pay a lab.</p><button className="btn btn-primary align-self-start" onClick={() => go(3, { verified: true, soil: true, role: 'tenant' })}>Simulate review, soil test and publication</button></>}
    {demo.step === 3 && <><label>Requested farm visit time<input type="datetime-local" className="form-control mb-3" value={demo.date} onChange={e => update({ date: e.target.value })} /></label><p>Status: <strong>{demo.visit}</strong></p><div className="d-flex flex-wrap gap-2"><button disabled={!demo.date} className="btn btn-outline-primary" onClick={() => update({ visit: 'requested', role: 'landowner' })}>Tenant requests visit</button><button disabled={demo.visit !== 'requested'} className="btn btn-primary" onClick={() => go(4, { visit: 'confirmed', role: 'landowner' })}>Landowner confirms visit</button><button disabled={demo.visit !== 'requested'} className="btn btn-outline-secondary" onClick={() => update({ visit: 'proposed', role: 'tenant' })}>Landowner proposes selected time</button><button disabled={demo.visit !== 'proposed'} className="btn btn-primary" onClick={() => go(4, { visit: 'confirmed' })}>Tenant accepts proposed time</button></div></>}
    {demo.step === 4 && <><label>Proposed terms<textarea rows={4} className="form-control mb-3" value={demo.terms} disabled={demo.proposal === 'accepted'} onChange={e => update({ terms: e.target.value })} /></label><label>Total lease value USD<input type="number" min={1} max={1000000} step="0.01" className="form-control mb-3" value={demo.amount} disabled={demo.proposal === 'accepted'} onChange={e => update({ amount: Number(e.target.value) })} /></label><p>Status: {demo.proposal} · The real proposal has a 72-hour response window.</p><div className="d-flex flex-wrap gap-2 mb-3"><button className="btn btn-outline-primary" disabled={!['draft','countered','declined'].includes(demo.proposal) || demo.terms.trim().length < 20 || demo.amount <= 0} onClick={() => update({ proposal: 'sent', role: 'tenant' })}>Landowner sends terms</button><button disabled={demo.proposal !== 'sent'} className="btn btn-primary" onClick={() => go(5, { proposal: 'accepted' })}>Tenant accepts</button><button disabled={demo.proposal !== 'sent'} className="btn btn-outline-danger" onClick={() => update({ proposal: 'declined' })}>Tenant declines</button></div><label>Counterproposal<textarea className="form-control mb-2" value={demo.counter} onChange={e => update({ counter: e.target.value })} /></label><button disabled={demo.proposal !== 'sent' || demo.counter.trim().length < 10} className="btn btn-outline-primary align-self-start mb-3" onClick={() => update({ proposal: 'countered', role: 'landowner' })}>Tenant requests changes</button><h3 className="h6">Demo negotiation messages</h3>{demo.messages.map((m,i) => <p key={i} className="border rounded p-2">{m}</p>)}<div className="d-flex gap-2"><input className="form-control" value={chat} onChange={e => setChat(e.target.value)} placeholder="Type a demo message" /><button className="btn btn-outline-dark" disabled={!chat.trim()} onClick={() => { update({ messages: [...demo.messages, `${demo.role}: ${chat.trim()}`] });setChat('') }}>Send</button></div></>}
    {demo.step === 5 && <>{['Landowner witness','Tenant witness'].map((label,index) => <label key={label} className="mb-3">{label} sample name<input className="form-control" value={demo.witnesses[index]} disabled={demo.signatures.some(Boolean)} onChange={e => update({ witnesses: demo.witnesses.map((value,i) => i === index ? e.target.value : value) })} /></label>)}<p>Each real party nominates its own witness with consent. Nominations do not verify witness identity.</p><button disabled={demo.witnesses.some(w => w.trim().length < 3)} className="btn btn-primary align-self-start" onClick={() => go(6)}>Continue to agreement</button></>}
    {demo.step === 6 && <><pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }} className="border rounded p-3">{agreement}</pre><label className="d-flex gap-2 mb-3"><input type="checkbox" checked={confirmAgreement} onChange={e => setConfirmAgreement(e.target.checked)} />I understand these are simulated signatures on a demo agreement.</label><div className="d-flex flex-wrap gap-2">{['Landowner','Tenant'].map((party,index) => <button key={party} className="btn btn-outline-primary" disabled={!confirmAgreement || Boolean(demo.signatures[index])} onClick={() => update({ signatures: demo.signatures.map((value,i) => i === index ? new Date().toISOString() : value) })}>{demo.signatures[index] ? `${party} demo signature recorded` : `Simulate ${party.toLowerCase()} signature`}</button>)}<button disabled={!demo.signatures.every(Boolean)} className="btn btn-primary" onClick={() => go(7, { role: 'tenant' })}>Continue to demo payment</button></div></>}
    {demo.step === 7 && <><p>Both simulated signatures are present. Payment is now unlocked in this walkthrough.</p><table className="table"><tbody><tr><th>Total demo payment</th><td>USD {demo.amount.toFixed(2)}</td></tr><tr><th>Landlease commission 3%</th><td>USD {commission.toFixed(2)}</td></tr><tr><th>Landowner allocation</th><td>USD {(demo.amount - commission).toFixed(2)}</td></tr></tbody></table><p>No real gateway is connected in this demo. No money will move.</p><button className="btn btn-primary align-self-start" onClick={() => go(8, { paid: true })}>Simulate successful payment and activate demo lease</button></>}
    {demo.step === 8 && <><p className="text-success fw-semibold">Demo lease active · Demo receipt DEMO-ONLY-{Math.abs(demo.plot)}</p><p>Simulated payment USD {demo.amount.toFixed(2)} · Commission USD {commission.toFixed(2)} · Landowner USD {(demo.amount - commission).toFixed(2)}</p><h3 className="h5">Season planning</h3><select className="form-select mb-2" value={crop} onChange={e => setCrop(e.target.value as keyof typeof cropGuides)}>{Object.keys(cropGuides).map(c => <option key={c}>{c}</option>)}</select><p>{cropGuides[crop].season}</p><ol>{cropGuides[crop].tasks.map(t => <li key={t}>{t}</li>)}</ol><label>Input budget USD<input type="number" min={0} className="form-control mb-2" value={budget} onChange={e => setBudget(e.target.value)} /></label><button className="btn btn-outline-primary align-self-start" onClick={() => update({ plan: `${crop} · Budget USD ${Number(budget).toFixed(2)}` })}>Save demo season plan</button>{demo.plan && <p className="mt-2">Saved: {demo.plan}</p>}<h3 className="h5 mt-4">Example equipment and inputs</h3><ul><li>Demo tractor hire provider — no booking or payment</li><li>Demo seed and fertilizer supplier — illustrative directory entry</li><li>Demo farm labour team — illustrative directory entry</li></ul><button className="btn btn-primary align-self-start" onClick={() => go(9)}>Continue to disputes and rating</button></>}
    {demo.step === 9 && <><label>Demo dispute description<textarea className="form-control mb-2" value={issue} onChange={e => setIssue(e.target.value)} /></label><div className="d-flex gap-2 mb-3"><button disabled={issue.trim().length < 10} className="btn btn-outline-primary" onClick={() => update({ dispute: issue, resolution: '', role: 'admin' })}>Report demo issue</button><button disabled={!demo.dispute} className="btn btn-outline-dark" onClick={() => update({ resolution: 'Demo resolution recorded by the simulated administrator.' })}>Simulate admin resolution</button></div>{demo.dispute && <p>Issue: {demo.dispute}<br />Status: {demo.resolution || 'Submitted for demo review'}</p>}<label>Demo rating<select className="form-select mb-3" value={demo.rating} onChange={e => update({ rating: e.target.value })}><option value="">Choose rating</option>{[5,4,3,2,1].map(n => <option key={n} value={n}>{n} stars</option>)}</select></label>{demo.rating && <p>Demo rating saved: {demo.rating}/5.</p>}<p>You have completed the presentation sequence. These records are browser-only examples.</p><Link className="btn btn-primary align-self-start" to="/workspace">Open the real account workspace</Link></>}
    </div>
    {error && <p role="alert" className="alert alert-danger mt-3">{error}</p>}
    <p className="small text-secondary mt-3">For the real system, document review, lab results, identities, signing terms and gateway settlement must be genuine and verified. The demo intentionally does not write to Supabase.</p>
  </section>
}
